### ISSUE TITLE
Custom Menu Bars Showing Opposite Theme (Mac)

### ISSUE THREAD

**Issue by Petchalxande** [rdbende/Sun-Valley-ttk-theme#1]
When running an App using the theme custom menu bars have the opposite display mode to what the app is showing i.e. in dark mode the text is showing dark on dark menu (as opposed to light text on dark menu, in light mode the text is showing light text on light menu.

Occurring on MacOS Big Sur 11.5 with the OS theme set to dark.

Love the theme and your work, thank you. Hope the above helps.

<img width="565" alt="Screenshot 2021-07-31 at 18 09 33" src="https://user-images.githubusercontent.com/60362599/127747437-b1b2dbff-693f-4933-a3b0-0916f7697aba.png">

**Comment by rdbende** [comment]
Hi!

Thanks for reporting this!
I made a [`mac-menu-fg`](https://github.com/rdbende/Sun-Valley-ttk-theme/archive/refs/heads/mac-menu-fg.zip) branch, please try it out, and tell me if it solves the problem.

Ps.: You made a really pretty GUI!

**Comment by Petchalxande** [comment]
Hey!

Darkmode showing correctly (see pic) but when set to lightmode still showing text incorrectly.

Also seems to be changing the system font on the menu, not sure if this is intended?

Thanks, I think you should be taking most of the credit there!

<img width="285" alt="Screenshot 2021-07-31 at 19 17 06" src="https://user-images.githubusercontent.com/60362599/127749059-bf95d066-fb08-49b4-8541-51d06833407c.png">

**Comment by rdbende** [comment]
Ok I now understand the problem. But I can't do anything with it. 😞 
I can't adjust the foreground color to the background color of the mac's built-in menu. The theme will set the menu foreground to black regardless of the OS theme, and it will not look good on a dark theme. You have to do this yourself, to find, what theme the OS uses, and adjust the menu colors based on it.

Font:
Yes the theme uses Segoe UI 10 everywhere. If not found, it falls back to the basic font. Since the theme can't recognize if a menu is actually a menubar, you need to set the font separately on the menubar to match the others.

```python
menubar = tk.Menu(root, name="apple", font=("TkMenuFont", 12))
```
or idk, what font size Mac uses for that menu

**Comment by Petchalxande** [comment]
Ahhh gotcha, thanks for looking into it! Really appreciate that.

Love your work, keep it up!!
