### ISSUE TITLE
Tcl App: `unknown color name "$colors(-selfg)"`

### ISSUE THREAD

**Issue by bsdooby** [rdbende/Sun-Valley-ttk-theme#122]
Dark Theme on Mac (macOS Sonoma), getting error `unknown color name "$colors(-selfg)"` when selecting row in a table view. App written in Tcl.

**Comment by bsdooby** [comment]
The following might fix it in `...sv_ttk/theme/dark.tcl` on line 441:
`#ttk::style map Treeview -background {selected "#292929"} -foreground {selected "#ffffff"}` or better yet
`ttk::style map Treeview -background {selected "#292929"} -foreground [subst {selected $colors(-selfg)}] `

**Comment by rdbende** [comment]
Hi, sorry for the delay. I didn't notice this bug unfortunately, because although it was broken on my Linux machine either, it did so silently, and have never thrown an error because of the invalid color string. Fortunately the fix was as simple as replacing the curly braces around the string with double quotes.
Also, this issue didn't affect the `sv-ttk` Python package, as it's currently not up-to-date with the `main` branch.

Anyway, it's been fixed now with bc81227

**Comment by bsdooby** [comment]
Great. THANK YOU!
