### ISSUE TITLE
Fluent design?

### ISSUE THREAD

**Issue by SchBenedikt** [rdbende/Sun-Valley-ttk-theme#131]
I have a quick question:
Is Fluent Design already being planned or considered?
Or does it just not work?
Best regards,
schBenedikt

**Comment by rdbende** [comment]
Hi, I'm not sure I understand your request. What Fluent design? I mean, isn't the current theme Fluent enough?

**Comment by SchBenedikt** [comment]
I probably expressed it incorrectly. I thought if a function is also being planned so that the background gets such an acrylic effect; so it is transparent and blurred.

**Comment by SchBenedikt** [comment]
I thought you might have an idea too....
Presumably this only really works with systems like WinUI 3.

**Comment by Andrew-J-Larson** [comment]
@SchBenedikt technically you can, if you use `pywinstyles` (set theme `acrylic`) with your GUI library (as long as it supports it).

However, I don't think `sv-ttk` is optimized for the acrylic look, purely because of this mention in the documentation here: [https://github.com/Akascape/py-window-styles/blob/main/Example_Documentation.md](https://github.com/Akascape/py-window-styles/blob/main/Example_Documentation.md#:~:text=Note%3A%20If%20you%20are%20applying%20themes%20like%20acrylic%2C%20then%20paint%20your%20UI%20window%20with%20black%20color%20using%20suitable%20methods.)
> Note: If you are applying themes like acrylic, then paint your UI window with black color using suitable methods.

So the theme would need to be altered to have a completely black background, and maybe some UI elements darkened to match the black background to match the acrylic look of other windows.
