### ISSUE TITLE
Question: ToolButton doesent actuallay have transperent background

### ISSUE THREAD

**Issue by sumeshir26** [rdbende/Sun-Valley-ttk-theme#16]
Hi, While using BlurWindow to get a acrilic effect in my app, it turns out that ToolButtons don't actually have transperent background. Are there any workarounds/code modifications to fix this?
![image](https://user-images.githubusercontent.com/68823982/149706960-61b2d0c0-3d77-4d21-96eb-51b572fa8a96.png)

Thanks!

**Comment by not-nef** [comment]
Well if you look closely, you can see that the normal buttons also dont have it

**Comment by not-nef** [comment]
![img](https://user-images.githubusercontent.com/68823982/149264450-e5e66b53-0b34-4cde-a89d-523a7acff291.png)

**Comment by not-nef** [comment]
@rdbende it would be soo nice pf you if you implement this!!

**Comment by rdbende** [comment]
Well, Tkinter (tcl/tk) doesn't support any transparency except that it has a `transparentcolor` attribute on Windows and Mac OS, and that it has an `alpha` option (yahh, it's really useful to make the title bar transparent). The `alpha` would make sense if it was only in areas where `transparentcolor` is present. So Tkinter sucks in this area. That's why I had to cheat.

The `ToolButton`, and the background of every widget isn't actually transparent, but the same color as the background of the one behind it, so it looks like it's transparent.
This background color should be the same everywhere, so instead of 'green' transparentcolor you can use the background color the theme uses (you can get it with `ttk.Style().lookup(".", "background")`) and make that color transparent instead.

Although I don't recommend this blur effect, because when you use transparentcolor than you can click through these "transparent" areas, which is really frustrating.

![image](https://user-images.githubusercontent.com/77941087/149819676-df5e43ff-c82f-4430-b132-72e44930a63d.png)

**Comment by not-nef** [comment]
Thank you!!

**Comment by not-nef** [comment]
@rdbende how did you make it so that it doesn't have the green lines around the labels?

**Comment by not-nef** [comment]
And you said you dont recommend using this blur effect. Is there anyone that you recommend using? (Sorry for bothering you with all these questions)

**Comment by rdbende** [comment]
I deleted the `app.config(bg="green")` line, 
and edited the following lines:

```python
app.wm_attributes("-transparent", "green")

[...]

time_selected_display = tkinter.Label(master = app, text = f'{timer_hours} Hours, {timer_minutes} Minutes, {timer_seconds} Seconds', font = ("Segoe UI Variable", 10), bg="green", fg="white")

[...]

time_display = tkinter.Label(master = app, text = f'{timer_hours} : {timer_minutes} : {timer_seconds}', font = ("Segoe UI Variable", 30), bg="green", fg="white")
```

to

```python
bg_color = ttk.Style().lookup(".", "background")

app.wm_attributes("-transparent", bg_color)

[...]

time_selected_display = tkinter.Label(master = app, text = f'{timer_hours} Hours, {timer_minutes} Minutes, {timer_seconds} Seconds', font = ("Segoe UI Variable", 10), bg=bg_color, fg="white")

[...]

time_display = tkinter.Label(master = app, text = f'{timer_hours} : {timer_minutes} : {timer_seconds}', font = ("Segoe UI Variable", 30), bg=bg_color , fg="white")
```
so first query the background color of the window, which is defined in the theme, and then set it everywhere instead of the "green" background color. Obviously you also need some function to update these colors when the theme changes.

Actually I like the `BlurWindow` module, and for Tkinter it is the only way to blur the background of the window. But to do that you have to use the `-transparentcolor `option, which lets you click through the window, which is really frustrating to me. However I don't know, if this is a feature or a bug.

**Comment by sumeshir26** [comment]
Thank you so much!
