### ISSUE TITLE
Title bar is not black

### ISSUE THREAD

**Issue by MMartin09** [rdbende/Sun-Valley-ttk-theme#3]
In the examples, the title bar of the window is also coloured black. However, when I test it out I always have a white title bar. 
![image](https://user-images.githubusercontent.com/16896363/129896454-dfa1bd25-30c6-47f2-ac53-83fce87c8d7e.png)

Note:
I am working on Windows 10.

**Comment by MrinmoyHaloi** [comment]
Yeah its true

**Comment by rdbende** [comment]
Now I can't even count on my 10 fingers how many people have asked me this. But I'll write that in the README as well.

With tkinter you can't control the appearance of the title bar. It depends on the operating system. Or you can create your own title bar if you want a unique look, but it’s not easy and comes with a lot of problems. On the screenshot it matches the theme, because I'm on KDE Plasma, and I made my own title bar for it.
