### ISSUE TITLE
TclError: can't invoke "winfo" command: application has been destroyed

### ISSUE THREAD

**Issue by marionAntech** [rdbende/Sun-Valley-ttk-theme#34]
Hello, I am getting a TCL Error when I run the example code. I am currently programming in Visual Studio code, I also used the pip install method. When i run the code the first time around it works without any isssue, however when i go to run it once again the TCL error appears. 

Do you know why this happens and/or a fix for this issue?

Attached is a picture of the calculator example code and the error that's being shown

![TCL Error](https://user-images.githubusercontent.com/108738102/177332082-e92965a8-c45b-4daf-adb3-a4d1dd1f26e0.png)

**Comment by rdbende** [comment]
This usually happens when something gets stuck in the mainloop and the application wasn't updated until quitting.
I realized, that using `root.update` in the examples was a really bad idea, as it can cause problems like this. You can try replacing `root.update` with `root.update_idletasks`. I believe it should work, but for me it works either way, so I can't test.

**Comment by marionAntech** [comment]
Thanks for the response. I did change it from root.update to root.update_idletasks and it still is throwing the error. I'm going to try to use a different IDE and see if that changes anything.

**Comment by marionAntech** [comment]
I am still unfortunately getting the error. I'm not quite sure why this is happening.

**Comment by sumeshir26** [comment]
For me when making TimerX, this error happened when I closed the app, and the program ended. The program ran normally. 😕

**Comment by rdbende** [comment]
@sumeshir26 I think it was because you bound the `<Configure>` event to the `sizechanged` function, which calls a `winfo` command 10 times in the worst case (I recommend you to refactor that function to avoid such bugs, anyways), and by the time they all have ran, the program have already closed.
But something else is happening here, because the test program works for me without any problems.
