### ISSUE TITLE
-show option of ttk::treeview

### ISSUE THREAD

**Issue by aplsimple** [rdbende/Sun-Valley-ttk-theme#4]
These two commands
   `option add *Treeview.show tree`
override the default `-show` option of ttk::treeview.

That's in Sun-Valley themes (dark & light) only.

And that's not very good. Drives a developer into mad searches, sort of "why my treeview not working as Tk default should?... while with other themes it works OK."

**Comment by rdbende** [comment]
As I wrote in the [documentation PDF](https://github.com/rdbende/Sun-Valley-ttk-theme/blob/master/DOCUMENTATION.pdf) it's a theme specific thing. Microsoft's design don't use the treeview headers, so I thought I should hide them in this theme too. But probably it would be better to show them, and put note in the README that they should be hidden.

**Comment by aplsimple** [comment]
I didn't get what's wrong with the treeview's images (icons?) as noted in
the documentation PDF
<https://github.com/rdbende/Sun-Valley-ttk-theme/blob/master/DOCUMENTATION.pdf>.
My Linux & Windows don't show any issues with them.  See e.g. in attachment.

To be honest, I had indeed troubles with the following lines, so I've just
comment them out:

        ttk::style element create Treeview.field image $I(card) \
>             -border 5


Maybe, you would play with them too.

**Comment by rdbende** [comment]
The problem is not with the icons. By default, the selected row in the treeview is indicated with a different color. I wanted to change this so that not only is it a different color, but an image is the background of the selected line, with rounding, and a vertical blue line at the beginning of the line, as you can see in the image.

However, the treeview somehow works weird, it duplicated the image well across the row, but it did it separately for column `#0`.

This is my problem.
![image](https://user-images.githubusercontent.com/77941087/132119592-2bad431d-d4cc-4612-bb3a-ae5d60d211ed.png)

**Comment by aplsimple** [comment]
got it at last, and wish you win in the battle with that stubborn treeview😊
