### ISSUE TITLE
How optimize app

### ISSUE THREAD

**Issue by chiften1371** [rdbende/Sun-Valley-ttk-theme#40]
Hello. I have a question. Why my program is very heavy and when I maximize and minimize the window, I get stuck on the screen for a few moments. Thank you for guiding me on how I can optimize the program.
here is my app:
[Foundation Input.zip](https://github.com/rdbende/Sun-Valley-ttk-theme/files/9214039/Foundation.Input.zip)

thanks

**Comment by rdbende** [comment]
Hi!

I assume you're experiencing this on Windows. Tkinter is known to be bad at displaying PNG images on Windows, but this theme uses them to draw the controls. That's why it takes so long to redraw widgets.
You can try the [gif-based branch](https://github.com/rdbende/Sun-Valley-ttk-theme/tree/gif-based), you might get better results with that, but it hasn't been updated in the 365 days.
Unfortunately this is all I can do in terms of optimization. Windows simply sucks!
