### ISSUE TITLE
Will it be possible to change accent colour in the theme based on the PC's accent colour? 

### ISSUE THREAD

**Issue by SlavBoi420** [rdbende/Sun-Valley-ttk-theme#63]
By default, for accented buttons and other stuff, this theme uses the default windows 11 blue accent colour. This looks good for most cases, but when the background is not particularly blue in colour, it kinda looks weird. So will it be possible to implement accent colours that change based on the user's accent colour, for more consistency?

**Comment by rdbende** [comment]
There's already #12 and #55 about this, but unfortunately it isn't easy to add accent color support.

Since this theme is based on PNG images, we would have to programmatically edit them to change their colors. You can find some hacking in #55, but that's still not perfect, and I don't really have time to work on it :((

**Comment by SlavBoi420** [comment]
Oh alright. Sorry I didn't really look into the other issues as much. Thanks for your reply!
