### ISSUE TITLE
Weird radiobutton

### ISSUE THREAD

**Issue by HuyHung1408** [rdbende/Sun-Valley-ttk-theme#81]
<img width="77" alt="image" src="https://user-images.githubusercontent.com/86362423/234748060-48804b02-2f64-4d1c-a25d-e814ea8a1499.png">

There's a black ring around the radio button, but it's not supposed the be there. Also, I don't like how the black box appears everywhere even though we are using the mouse, I know the black box is supposed to show when we are navigating with the keyboard, but it doesn't make sense when it shows every time, which looks clutter to me. 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/86362423/234748689-78e7da43-68b9-4982-b5e1-18fd35f53e3b.png">

**Comment by rdbende** [comment]
Unfortunately there's no distinction between mouse and keyboard focus in tkinter, so when an element is invoked with the mouse, it also gets the keyboard focus indicator.
While I agree that the focus ring makes clutter when navigating with the mouse, I can't remove it, because it would make this theme partially unusable. Maybe you can change this default behavior by overwriting some class bindings, but I'm not entirely sure.

**Comment by HuyHung1408** [comment]
Thanks, I will take a look at that.
